### ISSUE TITLE
UnauthorizedAccessException is thrown when running the build

### ISSUE THREAD

**Issue by rkaraivanov** [IgniteUI/igniteui-docfx#57]
Trying to build and run the project with `npm start` results in a UnauthorizedAccessException being thrown with the following stack trace:

```
Error:System.UnauthorizedAccessException: Access to the path 'C:\ProgramData\chocolatey\lib\docfx\tools\plugins_kc5k4jjw.gij\plugins' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at Microsoft.DocAsCode.Build.Engine.TemplateManager.Copy(Action`1 streamHandler, String filePath, Boolean overwrite)
   at Microsoft.DocAsCode.Build.Engine.TemplateManager.TryExportResourceFiles(IEnumerable`1 resourceNames, String outputDirectory, Boolean overwrite, String regexFilter)
   at Microsoft.DocAsCode.SubCommands.BuildCommand.BuildDocument(String baseDirectory, String outputDirectory)
   at Microsoft.DocAsCode.SubCommands.BuildCommand.Exec(SubCommandRunningContext context)
   at Microsoft.DocAsCode.Program.ExecSubCommand(String[] args)

**Comment by tiliev** [comment]
This error occurs because of the chocolatey package manager used to install docfx. Any attempt to access `C:\ProgramData\chocolatey` without elevated permissions will result in error. You can read additional information from point 1 [here](https://chocolatey.org/security#overall). [This](https://github.com/chocolatey/choco/issues/1048) is the issue in chocolatey repo where this is discussed. There are some work-arounds. They won't be fixing this since it is purposely implemented for security reasons.

**Comment by rkaraivanov** [comment]
Alright, then. We should mention that in the Getting Started section of the README
